apiVersion: v1
kind: Service
metadata:
  name: phoenix-app
  labels:
    app: phoenix-app
spec:
  type: {{ .Values.service.type }}
  selector:
    app: phoenix-app
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP